music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('', views.MusicHome.as_view(), name='music_index'),
    path('genre/<slug:genre_slug>/', views.MusicGenre.as_view(), name='genre'),
    path('page/<slug:page_slug>/', views.ShowPage.as_view(), name='page'),
    path('tag/<slug:tag_slug>/', views.ShowTag.as_view(), name='tag'),
    path('add_page/', views.AddPage.as_view(), name='add_page'),
    path('update_page/<slug:slug>', views.UpdatePage.as_view(), name='update_page'),
    path('delete_page/<slug:slug>', views.DeletePage.as_view(), name='delete_page'),
    ]

my_website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from my_website import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('music/', include('music.urls')),
    path('users/', include('users.urls', namespace='users')),
    #path('films/', include('films.urls')),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Сайт для разработки'

music/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Musician(models.Model):
    title = models.CharField(max_length=100, verbose_name='Имя исполнителя')
    slug = models.SlugField(max_length=250, unique=True, db_index=True, verbose_name='Slug')
    context = models.TextField(blank=True, verbose_name='Описание')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    age = models.IntegerField(blank=True, null=True, verbose_name='Возраст')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name='genre')
    genre = models.ForeignKey('Genre', on_delete=models.PROTECT, null=True, verbose_name='Жанр', related_name='genre')
    tagged = models.ManyToManyField('Tagged', default=None, blank=True, related_name='tagged')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', default=None, blank=True, null=True, verbose_name='Фото')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]
        verbose_name = 'Исполнитель'
        verbose_name_plural = 'Исполнители'

    def get_absolute_url(self):
        return reverse('music:page', kwargs={'page_slug': self.slug})


class Genre(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Жанр')
    slug = models.SlugField(max_length=250, db_index=True, unique=True)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('music:genre', kwargs={'genre_slug': self.slug})


class Tagged(models.Model):
    tag_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, null=True, db_index=True)

    def __str__(self):
        return self.tag_name

    def get_absolute_url(self):
        return reverse('music:tag', kwargs={'tag_slug': self.slug})


class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_files')

music/forms.py
from django import forms
from django.core.exceptions import ValidationError

from music.models import Musician, Genre, Tagged


class AddPageForm(forms.ModelForm):
    genre = forms.ModelChoiceField(queryset=Genre.objects.all(), empty_label='Жанр не выбран', label='Жанр')
    #tagged = forms.ModelChoiceField(queryset=Tagged.objects.all(), empty_label='Тег не выбран', label='Тег')


    class Meta:
        model = Musician
        fields = ['title', 'photo', 'slug', 'context',  'genre', 'age']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'context': forms.TextInput(attrs={'cols': 100, 'rows': 20})
        }
        labels = {'slug': 'URL'}

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError("Длина превышает 50 символов")

        return title


class UploadFilesForm(forms.ModelForm):
    file = forms.FileField(label='Фото')

music/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from music.forms import AddPageForm
from music.models import Musician, Tagged


class MusicHome(ListView):
    model = Musician
    template_name = 'music/music_index.html'
    context_object_name = 'pages'
    paginate_by = 3
    extra_context = {
        'title': 'Музыкальные исполнители',
        'genre_selected': 0,
    }

    def get_queryset(self):
        return Musician.objects.all()


class MusicGenre(ListView):
    template_name = 'music/music_index.html'
    context_object_name = 'pages'
    allow_empty = False

    def get_queryset(self):
        return Musician.objects.filter(genre__slug=self.kwargs['genre_slug']).select_related('genre')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre = context['pages'][0].genre
        context['title'] = 'Категория - ' + genre.name
        context['genre_selected'] = genre.pk
        return context


# def music_index(request):
#     singers = Musician.objects.all()
#     data = {
#             'title': 'Главная страница',
#             'singers': singers,
#             'cat_selected': 0,
#         }
#     return render(request, 'music/music_index.html', context=data)

class ShowTag(ListView):
    template_name = 'music/music_index.html'
    context_object_name = 'pages'
    allow_empty = True

    def get_queryset(self):
        return Musician.objects.filter(tagged__slug=self.kwargs['tag_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = Tagged.objects.get(slug=self.kwargs['tag_slug'])
        context['title'] = 'Тег: ' + tag.tag_name
        context['genre_selected'] = None
        return context


class ShowPage(DetailView):
    model = Musician
    template_name = 'music/music_page.html'
    context_object_name = 'page'
    slug_url_kwarg = 'page_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['page'].title
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(Musician, slug=self.kwargs[self.slug_url_kwarg])

# def show_page(request, page_slug):
#     page = get_object_or_404(Musician, slug=page_slug)
#     #page = Musician.objects.get(slug=page_slug)
#     data = {
#         'title': page.title,
#         'page': page,
#         'genre_selected': 1,
#     }
#     return render(request, 'music/music_page.html', data)


class AddPage(LoginRequiredMixin, CreateView):
    form_class = AddPageForm
    template_name = 'music/music_add_page.html'
    success_url = reverse_lazy('music:music_index')
    extra_context = {'title': 'Добавление статьи'}

    def form_valid(self, form):
        m = form.save(commit=False)
        m.author = self.request.user
        return super().form_valid(form)


class UpdatePage(UpdateView):
    model = Musician
    template_name = 'music/music_add_page.html'
    extra_context = {'title': 'Редактирование статьи'}
    fields = ['title', 'photo', 'slug', 'context',  'genre', 'age']
    success_url = reverse_lazy('music:music_index')


class DeletePage(DeleteView):
    model = Musician
    success_url = reverse_lazy('music:music_index')
    template_name = 'music/music_delete_page.html'

music/templates/music/music_add_page.html
{% extends 'main_page/base.html' %}
{% block content %}
<div class="form-info">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Отправить</button>
        </p>
    </form>
</div>
{% endblock %}

music/templates/music/music_delete_page.html
{% extends 'main_page/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить статью</button>
</form>
{% endblock %}

music/templates/music/music_index.html
{% extends 'main_page/base.html' %}
{% load music_tags %}
{% block content %}
<div class="conteiner">
    <div class="menu-bar">
        <ul class="leftchapters">
            {% if genre_selected == 0 %}
            <li class="selected">Все жанры</li>
            {% else %}
            <li><a href="{% url 'music:music_index' %}">Все жанры</a></li>
            {% endif %}

            {% show_genre genre_selected %}
            <!--            <li class="share">-->
            <!--            </li>-->
            {% show_tags %}
        </ul>
        <!--        <div class="tags">-->
        <!--            <ul>-->
        <!--                <li></li>-->
        <!--            </ul>-->
        <!--        </div>-->
    </div>
    <div class="content-text">
        <h1>{{ title }}</h1>
        <div class="list-articles">
            {% for p in pages %}
            <ul class="article">
                <li>
                    <div class="article-panel">
                        <p class="first">Категория: {{p.genre.name}}| Автор: {{ p.author.username |
                            default:"неизвестен"}}</p>
                        <p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
                    </div>
                </li>

                <div class="info-bar">
                    {% if p.photo %}
                    <p><img src="{{p.photo.url}}"></p>
                    {% endif %}
                    <li>
                        <h2>{{ p.title }}</h2>
                        {% autoescape off %}
                        <p>{{ p.context|linebreaks|truncatewords:40 }}</p>
                        {% endautoescape off %}
                        <p><a href="{{ p.get_absolute_url }}">Читать статью</a></p>
                        {% if not forloop.last %}
                        {% endif %}
                    </li>
                </div>
            </ul>
            {% endfor %}
            <a href="{% url 'music:add_page' %}">Добавить статью</a>
        </div>
    </div>

    {% endblock %}
</div>

{% block navigation %}
<div class="numbering">
    {% if page_obj.has_other_pages %}
    <nav class="list-pages">
        <ul>
            {% if page_obj.has_previous %}
            <li class="page-num">
                <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
            </li>
            {% endif %}

            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-num page-num-selected">{{ p }}</li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
            <li class="page-num">
                <a href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-num">
                <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

music/templates/music/music_page.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>{{ page.title }}</h1>

{% if page.photo %}
<p><img class="img-article-left" src="{{page.photo.url}}"></p>
{% endif %}

{{ page.context|linebreaks }}
<p>Возраст: {{ page.age }}</p>
<a href="{% url 'music:update_page' page.slug %}">Редактировать статью</a>
<a href="{% url 'music:delete_page' page.slug %}">Удалить статью</a>
{% endblock %}

music/templates/music/show_genre.html
{% for genre in genres %}
{% if genre.id == genre_selected %}
    <li class="selected">{{ genre.name }}</li>
{% else %}
<li><a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a></li>
{% endif %}
{% endfor %}

music/templates/music/show_tags.html
{% if tags %}
<div class="tags-conteiner">
    <p>Теги:</p>
    <ul class="tags-list">
        {% for tag in tags %}
        <li><a href="{{ tag.get_absolute_url }}">{{ tag.tag_name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endif %}