main_page/urls.py
from django.urls import path
from . import views

#app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('vacancy/', views.vacancy, name='vacancy'),
  ]

music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('', views.MusicHome.as_view(), name='music_index'),
    path('genre/<slug:genre_slug>/', views.MusicGenre.as_view(), name='genre'),
    path('page/<slug:page_slug>/', views.ShowPage.as_view(), name='page'),
    path('tag/<slug:tag_slug>/', views.ShowTag.as_view(), name='tag'),
    path('add_page/', views.AddPage.as_view(), name='add_page'),
    path('update_page/<slug:slug>', views.UpdatePage.as_view(), name='update_page'),
    path('delete_page/<slug:slug>', views.DeletePage.as_view(), name='delete_page'),
    ]

my_website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from my_website import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('music/', include('music.urls')),
    path('users/', include('users.urls', namespace='users')),
    #path('films/', include('films.urls')),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Сайт для разработки'

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change-done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_confirm_done.html', success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete')
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.http import HttpResponse
from django.shortcuts import render

menu = [
    {'title': 'Главная', 'url_name': 'index'},
    {'title': 'О сайте', 'url_name': 'about'},
    {'title': 'Контакты', 'url_name': 'contact'},
    {'title': 'Вакансии', 'url_name': 'vacancy'},
]


def index(request):
    return render(request, 'main_page/index.html')


def about(request):
    return HttpResponse('О нас')


def contact(request):
    return HttpResponse('Контакты')


def vacancy(request):
    return HttpResponse('Вакансии')

main_page/templates/main_page/base.html
{% load static %}
{% load music_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
<!--    <link type="text/css" href="{% static 'main_page/css/styles.css' %}" rel="stylesheet" />-->
    <link type="text/css" href="{% static 'main_page/css/main.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'main_page/css/music-conteiner.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'main_page/css/form-bar.css' %}" rel="stylesheet" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% block mainmenu %}
<div class="header">
    <ul id="mainmenu" class="mainmenu">
    {% for m in mainmenu %}
    <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
    {% endfor %}
    {% if user.is_authenticated %}
    <li class="last"><a href="{% url 'users:profile' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
    {% else %}
    <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
    {% endif %}
    </ul>
    <div class="clear"></div>
</div>
{% endblock %}

{% block content %}
{% endblock %}

{% block navigation %}
{% endblock %}
</body>
</html>

main_page/templates/main_page/index.html
{% extends 'main_page/base.html' %}
{% block content %}
    <h1>Главная страница</h1>
    <p>Наш проект - Наши новости</p>
    <a href="{% url 'music:music_index' %}">Музыка</a>

{% endblock %}