music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('', views.MusicHome.as_view(), name='music_index'),
    path('genre/<slug:genre_slug>/', views.MusicGenre.as_view(), name='genre'),
    path('page/<slug:page_slug>/', views.ShowPage.as_view(), name='page'),
    path('tag/<slug:tag_slug>/', views.ShowTag.as_view(), name='tag'),
    path('add_page/', views.AddPage.as_view(), name='add_page'),
    path('update_page/<slug:slug>', views.UpdatePage.as_view(), name='update_page'),
    path('delete_page/<slug:slug>', views.DeletePage.as_view(), name='delete_page'),
    ]

my_website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from my_website import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('music/', include('music.urls')),
    path('users/', include('users.urls', namespace='users')),
    #path('films/', include('films.urls')),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Сайт для разработки'

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change-done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_confirm_done.html', success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/m/%d', blank=True, null=True, verbose_name='Фото')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')

users/forms.py
import datetime
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Данный e-mail уже существует')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='email', widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5))))

    class Meta:
        model = get_user_model()
        fields = ['username', 'photo', 'email', 'first_name', 'last_name', 'date_birth']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'date_birth': 'Дата рождения',
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    def get_success_url(self):
        return reverse_lazy('index')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль'}

    def get_success_url(self):
        return reverse_lazy('music:music_index')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')

users/templates/users/login.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Авторизация</h1>
<div class="form-info">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.as_p }}
        <p>
            <button type="submit">Войти</button>
        </p>
    </form>
    <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Пароль успешно изменен</h1>
<p>Вы успешно изменили пароль, <a href="{% url 'users:profile' %}"> вернуться в свой аккаунт</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Смена пароля</h1>
<div class="form-info">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Заменить</button>
        </p>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Пароль изменен</h1>
<p>Поздравляем! Вы успешно сменили пароль. Используйте его для <a href="{% url 'users:login' %}">входа в систему</a></p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Ввод нового пароля</h1>
<div class="form-info">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Отправить</button>
        </p>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'main_page/base.html' %}
{% load i18n %}
{% block content %}
<h1>Сброс пароля</h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Восстановление пароля</h1>
<div class="form-info">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Отправить</button>
        </p>
    </form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Профиль</h1>
<div class="form-info">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Сохранить</button>
        </p>
    </form>
    <a href="{% url 'users:password_change' %}">Сменить пароль</a>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main_page/base.html' %}
{% block content %}
<h1>Регистрация</h1>
<div class="form-info">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.as_p }}
        <p></p>
        <button type="submit">Регистрация</button>
        </p>
    </form>
</div>
{% endblock %}